---
title: "損保1論文問題ネタ集"
author: "Yuki KAYABA"
date: "1/12/2023"
site: bookdown::bookdown_site
output:
  bookdown::gitbook: default
#output_dir: docs
#bookdown::gitbook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bookdown)
```

# はじめに

- 損保1における論文問題（いわゆる所見問題）に関連するトピックを問題形式を列挙しました。
- 一部コメント等も付していますが、個人的な見解です。
- 解答は提供していません。

# 新たな商品・補償の開発

## 個人向け感染症リスク

**問題1**
ある保険会社は特定の感染症（*1）に感染した際の入院・治療等にかかる費用を補償する個人向け保険の開発を検討している。当該商品の開発時に留意すべき点について、補償内容・引受方針・料率設定等の観点からアクチュアリーとしての所見を述べなさい。

（*1）新型コロナウイルス感染症のような世界的に感染拡大のおそれがある感染症を想定している

**問題1コメント**
新型コロナ感染拡大により各保険会社がコロナに関する新たな商品を開発した。社会環境の変化に応じて商品を開発・提供していくことは保険会社が果たすべき重要な役割であるが、コロナ保険は想定外の感染拡大等により結果として補償の削減や売り止めを余儀なくされたケースもあった。社会に対して適切な補償を提供しつつ、収益性・財務の健全性を確保していくためには事前の慎重な設計が必要であり、アクチュアリーが果たすべき役割も大きい。

[参考：株式会社justInCaseに対する行政処分について](https://lfb.mof.go.jp/kantou/kinyuu/pagekt_cnt_20220617001.html)

## インデックス保険

**問題2**
ある保険会社は近年の自然災害リスクの高まりを受け、新たにインデックス保険（*1）の保険の開発を検討している。当該商品の意義について、消費者・保険会社それぞれの視点から整理をしたうえで、開発にあたり留意すべき点について、アクチュアリーとしての所見を述べなさい。

（*1）損害と因果関係のある指標（震度や最大瞬間風速など）があらかじめ定めた基準を満たした場合に所定の額の保険金を支払う保険

[参考：保険商品審査事例集　令和4年1月](https://www.fsa.go.jp/status/hoken_sinsajireishu/20220121/2201shinsajireishu.pdf)

## インターネットチャネル向け商品

**問題3**
ある保険会社は現在自動車保険、火災保険、傷害保険などの個人向け商品を代理店経由で販売している。今般、デジタル技術の進展やデジタルネイティブ世代の出現といった社会環境の変化を踏まえ、スマートフォンアプリ経由での商品販売を検討している。

商品検討および販売にあたり留意すべき点について、商品設計（種目・補償内容・保険期間等）、料率設計、販売方針、販売開始後の収益管理等の観点からアクチュアリーとしての所見を述べよ。

[参考：H27年度アクチュアリー試験　損保1](https://www.actuaries.jp/lib/collection/books/H27/H27I.pdf)


# 既存商品の収支状況・収支改善

## 収支悪化への対応

**問題1**
自動車保険を扱うある保険会社は、ここ数年にわたり事故頻度が継続的に悪化していることを確認した。この状況において検討すべき事項および取るべき対応についてアクチュアリーとしての所見を述べなさい。

## 収益目標の設定

**問題2**
各保険種目の収益目標の設定にあたっては、コンバインド・レシオ、危険差損益、RoRといった指標を用いることが多いが、これらの指標について簡単に内容を説明したうえで、指標の選択において留意すべき観点についてアクチュアリーとしての所見を述べなさい。

# 料率細分化

## 料率細分化

**問題1**
他社が当社にはない料率区分を導入し、当社はある特定の区分について料率面で劣後することとなった。当該区分は営業戦略上当社がターゲットとしている区分であり、社内でも同様の料率区分新設を求める声が挙がっている。このような状況において検討・対応すべき事項についてアクチュアリーとしての所見を述べなさい。

[参考：2021年度アクチュアリー試験　損保1](https://www.actuaries.jp/lib/collection/books/2021/2021I.pdf)

## 割引の導入

**問題2**
ある保険会社では、新たな商品施策として「一定回数以上連続して当社で契約いただいているお客様はロイヤルカスタマーであるため割引を提供する」という案を検討することとなった。当該案について検討・留意すべき点を整理し、アクチュアリーとしての所見を述べなさい。

## 料率区分の統合

**問題3**
現行設けている料率区分について統合すべきと考えられるケースについて何点か挙げたうえで、検討にあたり留意すべき事項についてアクチュアリーとしての所見を述べなさい。


# 付加保険料

## さまざまなケースにおける付加保険料の設定

**問題1**
付加保険料の設定について、以下のケースにおいて留意すべき事項について記載せよ。

1. 新たな保険商品を開発するケース
2. 販売経路を代理店のみからインターネット販売にも拡大するケース
3. これまで任意付帯としていた特約を自動付帯とするケース
4. 当該商品について損害査定にAIによる画像認識を導入するケース
5. 契約者にドライブレコーダーやウェアラブル端末などを貸与するケース

## 事業費戦略

**問題2**
近年、各保険会社では事業費の削減を戦略目標に掲げている。事業費の削減が契約者および保険会社にもたらすメリット・デメリットを整理し、事業費戦略と付加保険料設定を一貫して行うために留意すべき事項についてアクチュアリーとしての所見を述べなさい。

[参考：MS&ADホールディングス　2022年度　第2回　インフォメーションミーティング　2022年11月22日](https://www.ms-ad-hd.com/ja/ir/ir_event/event/presentation/main/011111112/teaserItems1/0/linkList/0/link/221122IM_j.pdf)

[参考：東京海上ホールディングス　東京海上グループの経営戦略 2022年11月24日](https://www.tokiomarinehd.com/ir/event/presentation/2022/l6guv3000000g7x7-att/FY2022_Interim_IR_conference_j.pdf)

[参考：SOMPOホールディングス株式会社　中期経営計画の進捗　2022年11月25日](https://www.sompo-hd.com/-/media/hd/files/doc/pdf/ir/2022/20221125.pdf?la=ja-JP)

## 付加率割引（ポイント付与）

**問題1**
ある保険会社はウェブサイト上で保険契約を締結した契約者に対し、特定のポイント発行会社の会員である場合は保険料の一定割合をポイントとして還元することを検討している。このような仕組みを組成するにあたり留意すべき点について、アクチュアリーとしての所見を述べなさい。

[参考：保険商品審査事例集　令和2年2月](https://www.fsa.go.jp/status/hoken_sinsajireishu/20200210/2002shinsajireishu.pdf)

# その他料率算出

## 分割払の導入

**問題1**
ある保険会社は現在一時払のみで販売している商品（保険期間1年）について分割払の導入を検討している。導入あたり検討・留意すべき事項についてアクチュアリーとしての所見を述べなさい。

## 保険期間

**問題2**
ある保険会社では現在保険期間1年のみの商品を販売しているが、保険期間1年超の長期契約の導入を検討している。長期契約導入のメリット・デメリットを保険会社・契約者それぞれの観点から整理したうえで、料率算出上の留意点についてアクチュアリーとしての所見を述べなさい。

# 再保険・リスク管理

# その他

## 商品開発に係る内部管理体制

**問題1**
保険会社が保険商品の開発を行うにあたり、内部管理体制をどのように整備していくべきか、保険会社向けの総合的な監督指針の記載事項等も参考にしながら整理をしつつ、商品開発プロセスにおいてアクチュアリーが果たすべき役割について所見を述べなさい。

